# Generated by Django 2.0.4 on 2018-04-20 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('continents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.PositiveSmallIntegerField()),
                ('president', models.CharField(max_length=200)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='continents.ContinentModel')),
            ],
        ),
    ]
